name: Build and test
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Golang
        uses: actions/setup-go@v6

      - name: Build C
        run: gcc -Wall -Wextra csrc/init.c -o init

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...
